### ISSUE TITLE
Placeholder issue: Ingest sympy representation of ModelingToolkit and return PyTorch tensor with gradients and events

### ISSUE THREAD

**Issue by djinnome** [DARPA-ASKEM/sciml-service#108]
This is a placeholder issue until https://github.com/SciML/diffeqpy/issues/115  is exposed to the [DARPA ASKEM integration project](https://github.com/orgs/DARPA-ASKEM/projects/5) through github actions.

**Comment by djinnome** [comment]
JuliaHub hired a consultant to work on this.

**Comment by joshday** [comment]
@djinnome can this be closed?

**Comment by djinnome** [comment]
Yes!  Thanks for all the great work!
