### ISSUE TITLE
Rename `simulation-service` to `sciml-service`

### ISSUE THREAD

**Issue by fivegrant** [DARPA-ASKEM/sciml-service#121]
ASKEM has two simulation services, `pyciemss-service` and `simulation-service` but it causes some confusion that the latter isn't a more specific name like `sciml-service` or `julia-sim-service`. The renaming probably only needs to done in docker and the repo itself. The source might not need to be touched

**Comment by joshday** [comment]
Sounds reasonable to me.  Done.
