### ISSUE TITLE
Ensembles as parametric types of Simulate/Calibrate

### ISSUE THREAD

**Issue by jClugstor** [DARPA-ASKEM/sciml-service#152]
Right now the Ensemble structs are parametric, and hold a list of operations that are either simulate/calibrate objects. Knowing more about ensembles lately, I think this is not very useful, and ends up making the solving functions for the ensembles more complicated than they need to be. Especially ensemble calibrate, which really isn't a bunch of ensemble operations, it's more of it's own thing. 

I propose making two different structs, EnsembleSimulate, and EnsembleCalibrate.

**Comment by joshday** [comment]
Sounds good to me!

**Comment by jClugstor** [comment]
fixed by https://github.com/DARPA-ASKEM/sciml-service/pull/153
